---
name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test Java ${{ matrix.java }}
    permissions:
      checks: write
      pull-requests: write
    env:
      MAIN_JAVA_VER: 11
    strategy:
      matrix:
        java: [11, 20]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: maven

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: test python
      run: |
         pip3 install -r /home/runner/work/exhort-java-api/exhort-java-api/src/test/resources/tst_manifests/pip/pip_requirements_txt_ignore/requirements.txt
         pip3 freeze
         pip3 list
    - name: get Python location
      id: python-location
      run: |
        echo "python-bin-location=$(echo $pythonLocation)/bin" >> $GITHUB_OUTPUT
        ls -ltra $pythonLocation
        ls -ltra $pythonLocation/bin
        echo "pythonLocation ="
    - name: Verify the project and create coverage report
      env:
        EXHORT_PYTHON3_PATH: "${{steps.python-location.outputs.python-bin-location}}/python3"
        EXHORT_PIP3_PATH: "${{steps.python-location.outputs.python-bin-location}}/pip3"
      run: |
        mvn verify -Pits,cov -B -ff

    - name: Report test summary
      if: ${{ matrix.java == env.MAIN_JAVA_VER  && always() }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        test_changes_limit: 0
        files: ./target/junit-platform/TEST-junit-jupiter.xml

    - name: Upload coverage reports
      if: ${{ matrix.java == env.MAIN_JAVA_VER }}
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: ./target/site/jacoco/jacoco.xml
